#!/usr/bin/env bash

# CC-BY-NC-SA 2025 K9BFF


# gots 2 make sure
su_check() {
	if [[ $EUID -ne 0 ]]; then
		echo "sysop: needs to be run as sudo..."
		exit 1
	fi
}



# rebuild
if [[ $1 == "-r" ]]; then
	su_check
	nixos-rebuild switch |& nom



# upgrade
elif [[ $1 == "-u" ]]; then
	su_check
	nixos-rebuild switch --upgrade |& nom



# garbage collection
elif [[ $1 == "-d" ]]; then
	su_check
	read -p "sysop: garbage collection: are you sure? (y/N): " yesno
	if [[ $yesno == "y" ]]; then
		nix-collect-garbage -d |& nom
	else
		echo "sysop: couldn't confirm..."
		exit 1
	fi



# nix-shell
elif [[ $1 == "-p" ]]; then
	nix-shell -p $2 |& nom



# search
elif [[ $1 == "-s" ]]; then
	nix-search $2



# help
elif [[ $1 == "-h" ]]; then
	echo "sysop: system operations"
	echo
	echo "flag   operation"
	echo "-r     Rebuild"
	echo "-u     Upgrade"
	echo "-d     Garbage Collection"
	echo "-p     nix-shell install (temporary)"
	echo "-s     Search"
	echo "-h     Display this help"



# bad flag detector
else
	echo "sysop: $1: not a valid flag. Please see sysop -h for more information."
	exit 1
fi
