#!/usr/bin/env bash

# CC-BY-NC-SA 2025 K9BFF

# rebuild
if [[ $1 == "-r" ]]; then
	if [[ $EUID -ne 0 ]]; then
		echo "Needs to be run as sudo..." 
		exit 1
	else
		nixos-rebuild switch |& nom
	fi
fi

# upgrade
if [[ $1 == "-u" ]]; then
	if [[ $EUID -ne 0 ]]; then
		echo "Needs to be run as sudo..."
		exit 1
	else
		nixos-rebuild switch --upgrade |& nom
	fi
fi

# garbage collection
if [[ $1 == "-d" ]]; then
	if [[ $EUID -ne 0 ]]; then
		echo "Needs to be run as sudo..."
		exit 1
	else
		read -p "Are you sure? (y/N): " yesno
		if [[ $yesno == "y" ]]; then
			nix-collect-garbage -d |& nom
		else
			echo "Couldn't confirm..."
			exit 1
		fi
	fi
fi

# nix-shell
if [[ $1 == "-p" ]]; then
	nix-shell -p $2 |& nom
fi

# search
if [[ $1 == "-s" ]]; then
	nix-search $2
fi

# help
if [[ $1 == "-h" ]]; then
	echo "sysop: system operations"
	echo " "
	echo "-r     Rebuild"
	echo "-u     Upgrade"
	echo "-d     Garbage Collection"
	echo "-h     Display this help"
	echo "-p     nix-shell install (temporary)"
	echo "-s     Search"
fi


